# Generated by Django 2.2 on 2021-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210421_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
            preserve_default=False,
        ),
    ]
