# Generated by Django 2.2 on 2021-04-21 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
