# Generated by Django 2.2 on 2021-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210421_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
